# AWS properties
aws:
  access-key: '${{ secrets.AWS_ACCESS_KEY }}'
  secret-key: '${{ secrets.AWS_SECRET_KEY }}'
  region: '${{ secrets.AWS_REGION }}'
  endpoint: '${{ secrets.AWS_ENDPOINT }}'

server:
  port: 3306
